AppCalculator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.PartsView),
    path('', views.email),
    path('email.html', views.email, name='email'),
    path('thanks/', views.thanks, name='thanks'),
    path('feedback.html', views.thanks)
]

Bootstrap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppCalculator.urls')),
]

AppCalculator/models.py
from django.db import models

# Create your models here.

class PartOfApp(models.Model):
    part = models.CharField(max_length=150)
    fee = models.CharField(max_length=150)

    def __str__(self):
        return self.part

AppCalculator/forms.py
from django import forms

class ContactForm(forms.Form):

    # from_email = forms.EmailField(required=True)
    emailto = forms.EmailField(required=True)
    subjectt = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

AppCalculator/views.py
from django.http import HttpResponse
from django.shortcuts import render
from . models import PartOfApp
from django.core.mail import send_mail
# Create your views here.

def PartsView(request):
    parts = PartOfApp.objects.all()
    context = {'parts': parts}
    return render(request, 'index.html', context)

from django.core.mail import send_mail, BadHeaderError, EmailMessage, send_mass_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.views.decorators.csrf import csrf_exempt

# @csrf_exempt
def email(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subjectt']
            emailto = form.cleaned_data['emailto']
            from_email = 'ak@arcanite.ru'
            message = form.cleaned_data['message']
            try:
                message = "From: {email} \nMessage: {mesg}".format(email=str(emailto), mesg=str(message))
                subject2 = "Thanks for your feedback"
                message2 = "Our manager will contact you from 1 to 2 working days."
                send_mail(subject, message, from_email, ['ak@arcanite.ru'])
                send_mail(subject2, message2, from_email, [emailto])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('thanks')
    return HttpResponse(request, {'form': form})

def thanks(request):
    return HttpResponse('Thank you for your message')

AppCalculator/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#<div id="contactForm">#}
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    <form method="post">#}
{#        {{ form }}#}
{#    <div class="form-actions">#}
{#        <button id="post" type="submit">Send</button>#}
{#    </div>#}
        <div id="contactForm">
<form method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="cIHJ6grVD8YRrIHefbG8y3j6MIqj4FleOh1b8YKsj3Q9MlSlXKKFDwfgqNYmduA6">
    <label for="id_emailto">Emailto:</label><input type="email" name="emailto" required="" id="id_emailto">
    <label for="id_subjectt">Subjectt:</label><input type="text" name="subjectt" required="" id="id_subjectt">
    <label for="id_message">Message:</label><textarea name="message" cols="40" rows="10" required="" id="id_message"></textarea>
    <div class="form-actions">
        <button id="post" type="submit">Send</button>
    </div>
</form>

</div>
</form>
</form>
</div>
</body>
</html>

AppCalculator/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feedback Form</title>
</head>
<body>
<div>
 <form action='send/' method="get">
     <input type="text" value="{{ body }}" placeholder="Enter your Email">
     <input type="text" value="{{ body }}" placeholder="Enter WHAT U FUCKIN WANT">
     <button type="submit">SEND THIS SHIT</button>
 </form>

</div>
</body>
</html>

AppCalculator/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<meta charset="UTF-8">
<title>Calculator</title>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h2>Calculate the cost of your own app!</h2>
      <h5>Choose features that it must contain:</h5>
      {# Форма с селектором #}
      <div id="form">
        <select id="selector" class="custom-select" multiple>
          {% if parts %}
          {% for part in parts %}
          <option id="option" class="option" onclick="selected" value="{{ part.fee }}">{{ part }}</option>
          {% endfor %}
          {% else %}
          <h1>Error</h1>
          {% endif %}
          </select>
<script>
$("#selector").change(whatFee);
function whatFee() {
  var fee = 0;
  $('#selector option:selected').each(function () {
    fee += parseInt($(this).val());
    var beforeFee = "This app will cost - $" + fee;
    document.getElementById('output').innerHTML = String(beforeFee);
    });
    }
</script>
</div>
<p><h5><div id="output"></div></h5>
  </div>
  </div>
<!-- Форма обратной связи -->
<div id="contactForm">
  <form action="email.html" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="cIHJ6grVD8YRrIHefbG8y3j6MIqj4FleOh1b8YKsj3Q9MlSlXKKFDwfgqNYmduA6">
    <label  for="id_emailto">Your Email:</label><br><input type="email" name="emailto" required="" id="id_emailto">
    <br><label style="margin-top:.5rem;" for="id_subjectt">Subject:</label><br><input type="text" name="subjectt" required="" id="id_subjectt">
    <br><label style="margin-top:.5rem;" for="id_message">Message:</label><br><textarea name="message" cols="40" rows="10" required="" id="id_message"></textarea>
    <div class="form-actions">
      <button style="margin-top:.5rem;" id="post" type="submit">Send</button>
      </div>
      </form>
      </div>
      </div>
    </body>
    </html>

AppCalculator/templates/send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sent</title>
</head>
<body>
<h1>Sent an email</h1>
</body>
</html>